version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: Copy Android Licenses
          command: cp -r resources/android/licenses/. $ANDROID_HOME/licenses
      - run:
          name: build fix
          command: touch ~/.android/repositories.cfg
      - run: flutter doctor
      - run: flutter -v build apk --target lib/app/main.dart

  test:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build